services:
  db:
    image: mysql:8.0 
    container_name: mysql_db
    restart: always
    platform: linux/amd64 
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movielens
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d  # Mount scripts for DB initialization
      - ./csv:/var/lib/mysql-files  # Mount CSV files for data import

  python-api:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: python_api
    ports:
      - "5001:5000"
    depends_on:
      - db

  php:
    build: ./php
    container_name: php_app
    volumes:
      - ./php:/var/www/html
      - ./db:/var/www/html/scripts  # Mount scripts like before
    ports:
      - "8080:80"
    depends_on:
      - db
      - python-api  # Ensure Flask is running before PHP starts
    command: apachectl -D FOREGROUND

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

volumes:
  mysql_data: